language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
